# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/max/rp_ref/nand/vivado/nand.srcs/sources_1/bd/main_dsn/ip/main_dsn_processing_system7_0_0/main_dsn_processing_system7_0_0.xci
# IP: The module: 'main_dsn_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/max/rp_ref/nand/vivado/nand.gen/sources_1/bd/main_dsn/ip/main_dsn_processing_system7_0_0/main_dsn_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_dsn_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/max/rp_ref/nand/vivado/nand.srcs/sources_1/bd/main_dsn/ip/main_dsn_processing_system7_0_0/main_dsn_processing_system7_0_0.xci
# IP: The module: 'main_dsn_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/max/rp_ref/nand/vivado/nand.gen/sources_1/bd/main_dsn/ip/main_dsn_processing_system7_0_0/main_dsn_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_dsn_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
