# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/phy_cstrs.xdc

# Block Designs: bd/main_dsn/main_dsn.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_dsn || ORIG_REF_NAME==main_dsn} -quiet] -quiet

# IP: bd/main_dsn/ip/main_dsn_processing_system7_0_0/main_dsn_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_dsn_processing_system7_0_0 || ORIG_REF_NAME==main_dsn_processing_system7_0_0} -quiet] -quiet

# IP: bd/main_dsn/ip/main_dsn_AND_gate_0_0/main_dsn_AND_gate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_dsn_AND_gate_0_0 || ORIG_REF_NAME==main_dsn_AND_gate_0_0} -quiet] -quiet

# IP: bd/main_dsn/ip/main_dsn_axi_gpio_0_0/main_dsn_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_dsn_axi_gpio_0_0 || ORIG_REF_NAME==main_dsn_axi_gpio_0_0} -quiet] -quiet

# IP: bd/main_dsn/ip/main_dsn_axi_gpio_1_0/main_dsn_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_dsn_axi_gpio_1_0 || ORIG_REF_NAME==main_dsn_axi_gpio_1_0} -quiet] -quiet

# IP: bd/main_dsn/ip/main_dsn_xbar_0/main_dsn_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_dsn_xbar_0 || ORIG_REF_NAME==main_dsn_xbar_0} -quiet] -quiet

# IP: bd/main_dsn/ip/main_dsn_auto_pc_0/main_dsn_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_dsn_auto_pc_0 || ORIG_REF_NAME==main_dsn_auto_pc_0} -quiet] -quiet

# IP: bd/main_dsn/ip/main_dsn_ps7_0_axi_periph_0/main_dsn_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_dsn_ps7_0_axi_periph_0 || ORIG_REF_NAME==main_dsn_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/main_dsn/ip/main_dsn_rst_ps7_0_50M_0/main_dsn_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_dsn_rst_ps7_0_50M_0 || ORIG_REF_NAME==main_dsn_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: /home/max/rp_ref/nand/vivado/nand.gen/sources_1/bd/main_dsn/main_dsn_ooc.xdc
